# Install ora2pg
sudo apt-get install ora2pg

# Configure ora2pg by modifying the ora2pg.conf file
vi /etc/ora2pg/ora2pg.conf

# Update configuration with Oracle and PostgreSQL connection settings
ORACLE_DSN    dbi:Oracle:host=oracle_host;sid=ORCL;port=1521
ORACLE_USER   username
ORACLE_PWD    password
PG_DSN        dbi:Pg:host=postgres_host;dbname=mydb;port=5432


#!/bin/bash

# Set paths
ORACLE_CONF="/path/to/ora2pg.conf"
OUTPUT_DIR="/path/to/output.sql"

# Run ora2pg to export the BLOBs (e.g., images) from Oracle
ora2pg -c $ORACLE_CONF -t BLOB -o $OUTPUT_DIR

echo "Images exported from Oracle to $OUTPUT_DIR"

# Export only image table
TABLES        IMAGE_TABLE

# Set types conversion
DATA_TYPE     BLOB BYTEA

#!/bin/bash

# Path to the SQL file generated by ora2pg
SQL_FILE="/path/to/output.sql"

# PostgreSQL credentials
PG_USER="pguser"
PG_DB="pgdatabase"

# Import the data into PostgreSQL
psql -U $PG_USER -d $PG_DB -f $SQL_FILE

echo "Images imported into PostgreSQL"


INSERT INTO images_table (id, image_data)
VALUES
(1, pg_read_binary_file('/path/to/exported/image/file'));

# Verify count of images in Oracle and PostgreSQL
echo "Checking image count in Oracle and PostgreSQL"

oracle_image_count=$(sqlplus -s username/password@oracle_db <<EOF
SELECT COUNT(*) FROM IMAGE_TABLE;
EOF
)

postgres_image_count=$(psql -U pguser -d pgdatabase -c "SELECT COUNT(*) FROM images_table")

echo "Oracle image count: $oracle_image_count"
echo "PostgreSQL image count: $postgres_image_count"
